name: Publish to pub.dev

on:
  workflow_run:
    workflows: ['Release']
    types: [completed]

jobs:
  publish-ultra-flutter:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: dart/ultra_flutter

  publish-ultra-flutter-devtools:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: dart/ultra_flutter_devtools
